### ISSUE TITLE
Interpretation of eventDate and occurrenceStatus

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-mollusca-checklist#1]
Information for `occurrenceStatus` , the year of first and last observation (for `eventDate`) is not literally provided in the spreadsheet. However, we can deduct this information from the text, given in `first_observation_text` and `distribution_belgium_text`. We create three new columns in the raw data file (`first_observation`, `last_observation` and `occurrence_status`) and use the following criteria to populate the fields:

1. First observation:
We _always_ select the earliest date of observation, despite the fact that this occurrence is doubtful or not well documented.  If this is doubtful record is the _only_ recorded occurrence, then `occurrence_status` is set to `doubtful`.

2. Last observation:
We do not populate this field, unless this is (very) clear statement is made:

> "Only known from its first record" combined with "No records for waarnemingen.be" (for _Trochoidea elegans_)
> "Only known from the first record at Zeebrugge. Waarnemingen.be (consulted on 4 February 2019) reports several new observations of live animals from the same locality at Zeebrugge between 2014 and 2018." (_Massylaea vermiculata_)
> "There are currently no surviving populations in Belgium" (for _Xerosecta cespitum_)

We do not populate `end_year`  for:
> Only known from the first record at the botanical garden of the University of Gent. No records in Waarnemingen.be (consulted on 4 February 2019). Probably more widespread in other botanical gardens and greenhouses (_Hawaiia minuscula_).

3. Occurrence status:

Set to `present` by default. We only use `doubtful` if a clear statement is made about the uncertainty _and_ when there are no further observations on waarnemingen.be:

> "the records need confirmation" (for _Gittenbergia sororcula_)
> "there are no verifiable records" (for _Tandonia sowerbyi_)

**Comment by peterdesmet** [comment]
Looks sensible to me. Good that you add 3 columns rather than trying to parse the text.

**Comment by LienReyserhove** [comment]
Agreed with Thierry that this interpretation is OK
