### ISSUE TITLE
Mapping of original names

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-mollusca-checklist#12]
The dataset currently has relations between:

1. syn → acc: OK, but would be nice to differentiate between original names and subjective synonyms
2. acc → original: reverse link: informative, but duplicate
3. syn → origin: incorrect, do not have direct link

It is possible to only do one by using `heterotypicSynonym` and `homotypicSynonym`: http://rs.gbif.org/vocabulary/gbif/taxonomic_status.xml

# Example

1. Zonitoides arboreus (Say, 1817): ACCEPTED
2. Helix arborea Say, 1817: ORIGINAL NAME
3. Zonitoides azoricus Riedel, 1964: SYNONYM

## 1. Zonitoides arboreus

- taxonID: 1
- acceptedNameUsageID: 1
- ~~originalNameUsageID: 2~~: optional, would be duplicate info
- scientificName: Zonitoides arboreus (Say, 1817)
- acceptedNameUsage: Zonitoides arboreus (Say, 1817)
- ~~originalNameUsage: Helix arborea Say, 1817~~: optional, would be duplicate info
- taxonomicStatus: accepted

## 2. Helix arborea Say, 1817

- taxonID: 2
- acceptedNameUsageID: 1
- scientificName: Helix arborea Say, 1817
- acceptedNameUsage: Zonitoides arboreus (Say, 1817)
- taxonomicStatus: **homotypicSynonym**

## 3. Zonitoides azoricus Riedel, 1964

- taxonID: 3
- acceptedNameUsageID: 1
- scientificName: Zonitoides azoricus Riedel, 1964
- acceptedNameUsage: Zonitoides arboreus (Say, 1817)
- taxonomicStatus: **heterotypicSynonym**: since all original names are indicated, the rest will be heterotypic by default

**Comment by LienReyserhove** [comment]
Integrated accordingly
