### ISSUE TITLE
Move remarks to taxonRemarks

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-mollusca-checklist#15]
Two names contain remarks, which will cause them not to be matched by GBIF. I would move that remark to `taxonRemarks`:

> Ferussacia follicula Schröter, 1784 (erroneous spelling not used by Schröter, but used in about 30% of papers)
> Ferussacia folliculus Schröter, 1784 (erroneous spelling not used by Schröter, but used in about 70% of papers)

**Comment by LienReyserhove** [comment]
Integrated accordingly
