### ISSUE TITLE
Use uniform spelling for auct. non

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-mollusca-checklist#17]
There are three names:

```
Arion lusitanicus auctorum, non Mabille, 1868
Cernuella augustiniana auct., non Bourguignat, 1880
Cernuella cespitum auct., non Draparnaud, 1801
```

... that are "auctorum" (https://en.wikipedia.org/wiki/Auctorum), but they don't use the same way of indicating this. I would opt for `auct. non` for all (abbreviated + no comma)

**Comment by LienReyserhove** [comment]
Changed all to `auct. non`
