### ISSUE TITLE
Use occurrenceRemarks for lengthy descriptions of dates and locations

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-mollusca-checklist#8]
The fields `first_observation_text` and `distribution_belgium_text` in the [raw dataset](https://docs.google.com/spreadsheets/d/1hSXd6SZQUvI8uGbE_5-vmN8ZZz739D46HRt2aTFcb-s/edit#gid=0) include lengthy blocks of text. This information is summarized in the fields `first_observation` and `locality`/`locationID`/`countryCode` (the latter will relate to Belgium and is not included in the raw dataset). 
I wonder if all text information could be mapped under `occurrenceRemarks`. This would make this field a huge dump area of information of course...

**Comment by peterdesmet** [comment]
Could be dumped into `occurrenceRemarks` or added as separate information in the [description extension](http://rs.gbif.org/extension/gbif/1.0/description.xml). The advantage of dumping it in `occurrenceRemarks` is that it will be related to the distribution, so I would opt for that.
